# .travis.yml
dist: precise
language: php

matrix:
  include:
    - php: 7.2
    - php: 7.3


cache:
  directories:
    - vendor

before_script:
  - composer self-update
  - composer install --no-interaction
  - phpenv config-rm xdebug.ini

script:
  - vendor/phpunit/phpunit/phpunit tests/*
